    # Generated by Django 4.2 on 2023-05-14 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rabs',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='rabs',
            name='patronymic',
            field=models.CharField(max_length=20, verbose_name='Отчество'),
        ),
        migrations.AlterField(
            model_name='rabs',
            name='post',
            field=models.CharField(max_length=20, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='rabs',
            name='surname',
            field=models.CharField(max_length=20, verbose_name='Фамилия'),
        ),
    ]
