# Generated by Django 4.2 on 2023-05-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_rabs_name_alter_rabs_patronymic_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rabs',
            options={'verbose_name': 'Работники', 'verbose_name_plural': 'Работники'},
        ),
        migrations.AddField(
            model_name='rabs',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='Картинка'),
        ),
    ]
