# Generated by Django 4.2 on 2023-05-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_rabs_options_rabs_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rabs',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='F:\\Андрианова\\webclin\\images', verbose_name='Картинка'),
        ),
    ]
