# Generated by Django 4.2 on 2023-05-14 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_rabs_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rabs2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('surname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=20, verbose_name='Отчество')),
                ('post', models.CharField(max_length=20, verbose_name='Должность')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Картинка')),
            ],
            options={
                'verbose_name': 'Работники',
                'verbose_name_plural': 'Работники',
            },
        ),
        migrations.AlterField(
            model_name='rabs',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Картинка'),
        ),
    ]
