# Generated by Django 4.2 on 2023-05-14 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rabs2_alter_rabs_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rabs2',
            options={'verbose_name': 'Работники2', 'verbose_name_plural': 'Работники2'},
        ),
    ]
