# Generated by Django 4.2 on 2023-05-14 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_zap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zap',
            name='phone',
            field=models.BigIntegerField(verbose_name='Телефон'),
        ),
    ]
