# Generated by Django 4.2 on 2023-05-20 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='rabs',
            name='id1',
            field=models.BigIntegerField(null=True, verbose_name='Id'),
        ),
    ]
