# Generated by Django 4.2 on 2023-05-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rabs_id1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rabs',
            name='id1',
            field=models.CharField(max_length=20, null=True, verbose_name='Id'),
        ),
    ]
