# Generated by Django 4.2 on 2023-05-20 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_rabs_id1'),
    ]

    operations = [
        migrations.AddField(
            model_name='zap',
            name='doctor',
            field=models.CharField(max_length=20, null=True, verbose_name='Имя'),
        ),
    ]
