# Generated by Django 4.2 on 2023-05-21 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_zap_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zap1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('phone', models.BigIntegerField(verbose_name='Телефон')),
                ('doctor', models.CharField(default='Кузьмичева Дарья Андреевна', max_length=100, verbose_name='Доктор')),
            ],
            options={
                'verbose_name': 'ЗаписьКузьмичева',
                'verbose_name_plural': 'ЗаписиКузьмичева',
            },
        ),
        migrations.CreateModel(
            name='Zap2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('phone', models.BigIntegerField(verbose_name='Телефон')),
                ('doctor', models.CharField(default='Покровский Антон Иванов', max_length=100, verbose_name='Доктор')),
            ],
            options={
                'verbose_name': 'ЗаписьПокровский',
                'verbose_name_plural': 'ЗаписиПокровский',
            },
        ),
        migrations.CreateModel(
            name='Zap3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('phone', models.BigIntegerField(verbose_name='Телефон')),
                ('doctor', models.CharField(default='Затина Альфия Габделхаевна', max_length=100, verbose_name='Доктор')),
            ],
            options={
                'verbose_name': 'ЗаписьЗатина',
                'verbose_name_plural': 'ЗаписиЗатина',
            },
        ),
        migrations.DeleteModel(
            name='Zap',
        ),
    ]
